version: '3.7'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=qwerty
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=qwerty
  web:
    build: .
    command: python /usr/src/codraw/manage.py runserver 0.0.0.0:8010
    volumes:
      - .:/usr/src/codraw
      - /etc/codraw:/etc/codraw
    ports:
      - 8010:8010
    depends_on:
      - db
volumes:
  postgres_data:



#  front:
#    build: ./cofront
#    command: python /usr/src/codraw/manage.py runserver 0.0.0.0:8010
#    volumes:
#      - .:/usr/src/codraw
#    ports:
#      - 8010:8010
#    depends_on:
#      - db