version: '3.7'

volumes:
    postgres_data: {}

services:
    redis:
        image: redis:7.0-rc3-alpine3.15
        ports:
            - "${REDIS_PORT}:6379"
    postgres:
        image: postgres:13.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data
        env_file: .env
    backend:
        build:
            context: .
        depends_on:
            - postgres
        volumes:
            - .:/app
        command: /start.sh
        entrypoint: /entrypoint.sh
        restart: always
        env_file: .env
        ports:
            - "8000:8000"


#  front:
#    build: ./cofront
#    command: python /usr/src/codraw/manage.py runserver 0.0.0.0:8010
#    volumes:
#      - .:/usr/src/codraw
#    ports:
#      - 8010:8010
#    depends_on:
#      - db