# Generated by Django 3.2.7 on 2022-09-27 20:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codraw', '0004_alter_rating_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'verbose_name': 'Аниме', 'verbose_name_plural': 'Аниме'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанры', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Рейтинг', 'verbose_name_plural': 'Рейтинг'},
        ),
        migrations.AlterField(
            model_name='anime',
            name='added_episodes',
            field=models.IntegerField(default=0, verbose_name='Количество выпущенных эпизодов'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='episodes_count',
            field=models.IntegerField(default=-1, verbose_name='Количество эпизодов(-1 - неизвестно)'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(related_name='anime', to='codraw.Genre', verbose_name='Жанры'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='image',
            field=models.ImageField(upload_to='media/anime/images', verbose_name='Изображение(240x400)'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='name',
            field=models.CharField(blank=True, max_length=60, verbose_name='Название на русском'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='original_name',
            field=models.CharField(max_length=255, verbose_name='Оригинальное название'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='premiere_date',
            field=models.DateField(blank=True, verbose_name='Дата премьеры'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='rating_calc',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Калькуляция рейтинга'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='raw_rating',
            field=models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Дефолтный рейтинг'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='raw_visits',
            field=models.PositiveBigIntegerField(blank=True, verbose_name='Дефолтное количетсво посещений'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='status',
            field=models.CharField(choices=[('AN', 'Анонсировано'), ('ON', 'Онгоинг'), ('RE', 'Завершено')], default='AN', max_length=2, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание жанра'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Название жанра'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codraw.anime', verbose_name='Аниме'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка'),
        ),
    ]
