# Generated by Django 3.2.7 on 2022-04-08 15:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codraw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60)),
                ('original_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('premiere_date', models.DateField(blank=True)),
                ('status', models.CharField(choices=[('AN', 'Announced'), ('ON', 'Ongoing'), ('RE', 'Released')], default='AN', max_length=2)),
                ('episodes_count', models.IntegerField(default=-1)),
                ('added_episodes', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='', verbose_name='media/anime/images')),
                ('raw_rating', models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('raw_visits', models.PositiveBigIntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codraw.anime')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='genre',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_genre_name'),
        ),
        migrations.AddField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(related_name='anime', to='codraw.Genre'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('owner', 'anime'), name='unique_anime_user'),
        ),
        migrations.AddConstraint(
            model_name='anime',
            constraint=models.UniqueConstraint(fields=('original_name',), name='unique_anime_original_name'),
        ),
    ]
