# Generated by Django 3.2.7 on 2022-04-11 02:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codraw', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='rating_calc',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
