version: '3.7'

volumes:
    postgres_data: {}
    frontend_static:
    backend_static:
    backend_media:

services:
    nginx:
        build:
            context: ./nginx
        volumes:
            - frontend_static:/dist/frontend/static
            - backend_static:/dist/backend/static
            - backend_media:/dist/backend/media
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - backend
    redis:
        image: redis:7.0-rc3-alpine3.15
        expose:
            - "${REDIS_PORT}"
    postgres:
        image: postgres:13.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data
        env_file: .env
    backend:
        build:
            context: ../backend
            dockerfile: ../backend/Dockerfile.prod
        depends_on:
            - postgres
        volumes:
            - backend_static:/backend/static
            - backend_media:/backend/media
        command: /gunicorn.sh
        entrypoint: /entrypoint.sh
        env_file: .env
        expose:
            - "8000"
    front:
        build:
            context: ../frontend
            dockerfile: ../frontend/Dockerfile.prod
        depends_on:
            - backend
        volumes:
            - frontend_static:/frontend/dist
        env_file: .env
        expose:
            - "8080"